#!/usr/bin/env bun
// Build script: bundle CF Worker + embed schema → compile native binary
import { writeFileSync, readFileSync } from "fs";
import { join } from "path";

const ROOT = import.meta.dir;
const WORKER_ENTRY    = join(ROOT, "worker/src/index.ts");
const WORKER_BUNDLE   = join(ROOT, "daemon/worker-bundle.ts");
const SCHEMA_SRC      = join(ROOT, "schema.sql");
const SCHEMA_BUNDLE   = join(ROOT, "daemon/schema-bundle.ts");
const DIST            = join(ROOT, "dist");
const BUN             = "/opt/homebrew/bin/bun";
console.log("=== imsg-forwarder build ===\n");

// 1. Bundle the CF Worker
console.log("[1/4] Bundling CF Worker...");
const result = await Bun.build({
  entrypoints: [WORKER_ENTRY],
  target: "browser",
  format: "esm",
  minify: true,
});

if (!result.success) {
  console.error("Worker bundle failed:");
  for (const l of result.logs) console.error(" ", l);
  process.exit(1);
}
const workerJs = await result.outputs[0]!.text();
console.log(`  Bundled (${(workerJs.length / 1024).toFixed(1)} KB)`);

// 2. Embed worker bundle
console.log("[2/4] Embedding worker bundle...");
writeFileSync(WORKER_BUNDLE, `// Auto-generated by build.ts — do not edit\nexport const WORKER_BUNDLE = ${JSON.stringify(workerJs)};\n`);
console.log("  Written to daemon/worker-bundle.ts");

// 3. Embed schema
console.log("[3/4] Embedding schema...");
const schemaSql = readFileSync(SCHEMA_SRC, "utf8");
writeFileSync(SCHEMA_BUNDLE, `// Auto-generated by build.ts — do not edit\nexport const SCHEMA_SQL = ${JSON.stringify(schemaSql)};\n`);
console.log("  Written to daemon/schema-bundle.ts");

// 4. Compile daemon to native binaries
console.log("[4/4] Compiling daemon...");
Bun.spawnSync(["mkdir", "-p", DIST]);

const targets: [string, string][] = [
  ["bun-darwin-arm64", "imsg-forwarder"],
  ["bun-darwin-x64",   "imsg-forwarder-x64"],
];

for (const [target, outName] of targets) {
  const outFile = join(DIST, outName);
  const proc = Bun.spawnSync(
    [BUN, "build", "--compile", "--minify", "--target", target, join(ROOT, "daemon/index.ts"), "--outfile", outFile],
    { stdout: "inherit", stderr: "inherit" }
  );
  if (proc.exitCode !== 0) {
    console.error(`  Failed to compile ${outName}`);
    process.exit(1);
  }
  console.log(`  ${outName} → dist/${outName}`);
}

console.log("\nBuild complete!");
console.log("  Install (copy + codesign required after every update):");
console.log("    sudo cp dist/imsg-forwarder /usr/local/bin/imsg-forwarder");
console.log(`    sudo codesign --force --sign - --identifier "com.imsg-forwarder" --requirements '=designated => identifier "com.imsg-forwarder"' /usr/local/bin/imsg-forwarder`);
console.log("  Then: copy com.imsg-forwarder.plist.example → ~/Library/LaunchAgents/com.imsg-forwarder.plist");
